//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnquiryForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnquirydbEntities : DbContext
    {
        public EnquirydbEntities()
            : base("name=EnquirydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCandidateDetail> tblCandidateDetails { get; set; }
        public virtual DbSet<tblEnquiry> tblEnquiries { get; set; }
        public virtual DbSet<tblEnquiryDetail> tblEnquiryDetails { get; set; }
        public virtual DbSet<tblInformation> tblInformations { get; set; }
        public virtual DbSet<tblTraining> tblTrainings { get; set; }
        public virtual DbSet<viewDetail> viewDetails { get; set; }
        public virtual DbSet<tblEducationDetail> tblEducationDetails { get; set; }
    }
}
