//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnquiryForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCandidateDetail
    {
        public tblCandidateDetail()
        {
            this.tblEnquiryDetails = new HashSet<tblEnquiryDetail>();
            this.tblEducationDetails = new HashSet<tblEducationDetail>();
        }
    
        public int Candidate_id { get; set; }
        public string Candidate_name { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string emailId { get; set; }
    
        public virtual ICollection<tblEnquiryDetail> tblEnquiryDetails { get; set; }
        public virtual ICollection<tblEducationDetail> tblEducationDetails { get; set; }
    }
}
