//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnquiryForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnquiryDetail
    {
        public int Enquiry_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public Nullable<System.DateTime> Enquiry_Date { get; set; }
        public string EnquiryFor { get; set; }
        public string Lead_sources { get; set; }
        public string EnquiryBy { get; set; }
    
        public virtual tblCandidateDetail tblCandidateDetail { get; set; }
    }
}
