//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnquiryForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTraining
    {
        public int Training_id { get; set; }
        public string Training_course { get; set; }
    }
}
